src/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.generic import RedirectView

from users.views import signup

favicon_view = RedirectView.as_view(url='/static/base/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('start/', signup, name='web_signup'),
    path('broadcast/', include('broadcast.urls')),
    path('courses/', include('courses.urls')),
    path('forms/', include('forms.urls')),
    path('favicon.ico', favicon_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Parcel админка'

src/broadcast/urls.py
from django.urls import path

from broadcast import views

app_name = 'broadcast'

urlpatterns = [
    path('prepare-msg/', views.render_send, name='prepare_message'),
    path('resend-msg/<int:msg_id>', views.resend_msg, name='resend_msg'),
    path('send/', views.send, name='send'),
]

src/broadcast/models.py
from django.core.validators import validate_image_file_extension
from django.db import models

from broadcast.utils.uploaders import message_media_directory
from general.models import BaseModel
from general.validators import (
    validate_video_extension, validate_file_size,
    validate_dimensions, validate_thumbnail_size
)
from django.utils import timezone

THUMBNAIL_HELP_TEXT = """
The thumbnail should be in JPEG format and less than 200 kB in size. 
A thumbnail\'s width and height should not exceed 320.
"""


class Message(BaseModel):
    text = models.TextField(verbose_name='Текст')
    video = models.FileField(verbose_name='Видео', null=True,
                             blank=True, upload_to=message_media_directory,
                             validators=[validate_video_extension, validate_file_size],
                             help_text='Не больше 50 мб')
    image = models.ImageField(verbose_name='Картинка', upload_to=message_media_directory,
                              null=True, blank=True,
                              validators=[validate_image_file_extension],
                              help_text=THUMBNAIL_HELP_TEXT)
    link = models.CharField(max_length=255, null=True, blank=True, verbose_name='Cсылка')

    delivery_start_time = models.DateTimeField('Начало отправки', default=timezone.now)
    delivery_end_time = models.DateTimeField('Окончание отправки', null=True, blank=True)
    notes = models.TextField(verbose_name='Заметки к сообщению', blank=True, null=True)

    def __str__(self):
        return f'MessageId{self.id}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MessageHistory(BaseModel):
    message = models.ForeignKey(Message, verbose_name='Сообщение', on_delete=models.CASCADE)
    contact = models.ForeignKey('contacts.Contact', verbose_name='Получатель', on_delete=models.CASCADE)
    response = models.TextField(blank=True, null=True, verbose_name='Ответ')
    delivered = models.BooleanField(verbose_name='Отправлено')

    def __str__(self):
        return f'Отправка №{self.id}'

    class Meta:
        verbose_name_plural = 'Отправленное сообщение'
        verbose_name = 'Отправленные сообщения'

src/broadcast/forms.py
from django import forms
from broadcast import models


class BroadcastForm(forms.ModelForm):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    is_feedback = forms.BooleanField(required=False, label='Фидбек')

    def __init__(self, *args, **kwargs):
        super(BroadcastForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'style': 'width: 800px;'})
        self.fields['notes'].widget.attrs.update({'style': 'width: 800px;'})
        self.fields['link'].widget.attrs.update({'style': 'width: 500px;'})

    class Meta:
        model = models.Message
        fields = ('text', 'video', 'image', 'link', 'notes')

src/broadcast/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from broadcast import models
from broadcast.forms import BroadcastForm
from broadcast.tasks import send_to_queue
from contacts import models as contact_models


def resend_msg(request, msg_id):
    """
    Renders sent message for resending
    """
    message = models.Message.objects.get(pk=msg_id)
    contacts = [x.contact for x in message.messagehistory_set.all()]
    form = BroadcastForm(initial={
        '_selected_action': [contact.id for contact in contacts],
        'text': message.text,
        'video': message.video,
        'image': message.image,
        'link': message.link,
        'notes': message.notes,
    })
    context = {
        'entities': contacts,
        'form': form,
        'referer': request.META['HTTP_REFERER'],
    }
    return render(request, "broadcast/send.html", context=context)


def render_send(request):
    """
    Render send template for specific contact
    """
    selected = request.GET.getlist('_selected_action')

    if 'all' in request.GET:
        contacts = contact_models.Contact.objects.all()
    else:
        contacts = contact_models.Contact.objects.filter(pk__in=selected)

    form = BroadcastForm(initial={'_selected_action': [x.id for x in contacts]})
    context = {
        'entities': contacts,
        'form': form,
        'referer': request.META['HTTP_REFERER'],
    }

    return render(request, 'broadcast/send.html', context=context)


def send(request):
    """
    Handles POST Requests.
    Save submitted message and pass to celery for sending
    """
    message = models.Message.objects.create(
        text=request.POST.get('text'),
        video=request.FILES.get('video'),
        image=request.FILES.get('image'),
        link=request.POST.get('link'),
        notes=request.POST.get('notes'),
    )

    selected = request.POST.getlist('_selected_action')
    is_feedback = request.POST.get('is_feedback')
    config = {
        'ids': selected,
        'message_id': message.id,
        'is_feedback': is_feedback,
    }

    send_to_queue.delay(config)

    return HttpResponseRedirect(request.POST.get('referer'))

src/broadcast/templates/broadcast/promo_text.html
<b>{{ promo.title }}</b>

{{ promo.description|safe }}
{% if promo.display_link %}
<a href="{{ promo.link }}">👉 Записаться на курс / Kurga yozilish</a>
{% endif %}

src/broadcast/templates/broadcast/send.html
{% extends "admin/base_site.html" %}

{% block content %}
<h1>Отправить сообщение</h1>
<table>
    <tbody>
    <tr>
        <td style="padding: 0;">
            <form action="{% url 'broadcast:send' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <input type="hidden" name="referer" value="{{ referer }}" />
                  {% for hidden_field in form.hidden_fields %}
                    {% if hidden_field.errors %}
                      <ul>
                        {% for error in hidden_field.errors %}
                          <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
                        {% endfor %}
                      </ul>
                    {% endif %}
                    {{ hidden_field }}
                  {% endfor %}
                <table style="margin-bottom: 15px;">
                {% for field in form.visible_fields %}
                      <tr>
                        <th>{{ field.label_tag }}</th>
                        <td>
                          {{ field.errors }}
                          {{ field }}
                          <div style="font-size: 12px;">{{ field.help_text }}</div>
                        </td>
                      </tr>
                {% endfor %}
                </table>
                <input type="submit" value="Отправить" />
            </form>
        </td>

        <td style="border: none; padding: 0 0 0 1em;" >
            <ul>
                <strong>Вы собираетесь отправить сообщение следующим людям:</strong>
                {{ entities|unordered_list }}
            </ul>
        </td>
    </tr>
    </tbody>
</table>
{% endblock %}