src/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.generic import RedirectView

from users.views import signup

favicon_view = RedirectView.as_view(url='/static/base/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('start/', signup, name='web_signup'),
    path('broadcast/', include('broadcast.urls')),
    path('courses/', include('courses.urls')),
    path('forms/', include('forms.urls')),
    path('favicon.ico', favicon_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Parcel админка'

src/users/forms.py
from django import forms

from users import models
from courses import models as course_models


class LeadForm(forms.ModelForm):
    class Meta:
        model = models.Lead
        fields = ['first_name', 'last_name', 'phone', 'city', ]


class StudentAdmin(forms.ModelForm):
    course = forms.ModelMultipleChoiceField(
        queryset=course_models.Course.objects.all(),
        widget=forms.SelectMultiple,
        required=False
    )

    def get_initial_for_field(self, field, field_name):
        """
        Mark current courses of student in Admin panel
        """
        if self.instance and self.instance.id and hasattr(self.instance, 'courses'):
            courses = tuple([x.id for x in self.instance.courses.all()])
            self.fields['course'].initial = courses

            return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        """
        Redefined save method to support Multiple Choice of courses in Admin panel
        """
        instance = super().save()
        instance.courses.set(self.cleaned_data['course'])
        # Add a method to the form to allow deferred
        # saving of m2m data.
        self.save_m2m = self._save_m2m
        return instance

    class Meta:
        model = models.Lead
        exclude = ('invite_link',)

src/dashboard/templates/dashboard/assign_to_course.html
{% extends 'admin/base_site.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p>
        Are you sure you want to execute this action on the selected items?
    </p>
    {% for entity in entities %}
        <input type="hidden" name="_selected_action" value="{{ entity.pk }}" />
    {% endfor %}
    <label class="required" for="id_course">Course:</label>

    <select name="course" required id="id_course" multiple>
        {% for course in courses %}
            <option value={{course.id}}>{{course.name}}</option>
        {% endfor %}
    </select>

    <input type="hidden" name="action" value="assign_to_course" />
    <input type="submit" name="assign" value="Assign Course"/>
</form>
{% endblock %}

src/dashboard/templates/dashboard/lesson_info.html
<strong>{{lesson.title}}</strong>

{{lesson.info}}

src/dashboard/templates/dashboard/message_form.html
<a href="{% url 'dashboard:send_message' %}?_selected_action={{data.student.id}}">💬</a>